version: '3.8'

services:

  influxdb_source:
    image: influxdb:2.7
    restart: always
    container_name: influxdb_source
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=graphql-experiment
      - DOCKER_INFLUXDB_INIT_BUCKET=graphql-power
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - monitoring

  grafana_visualization:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb_source
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

  mongodb_destination:
    image: mongo:latest
    container_name: mongodb_destination
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db

volumes:
  influxdb-data: {}
  influxdb-config: {}
  grafana-data: {}
  mongodb_data:

networks:
  monitoring:
    driver: bridge
