version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=graphql-experiment
      - DOCKER_INFLUXDB_INIT_BUCKET=graphql-power
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  influxdb-data: {}
  influxdb-config: {}
  grafana-data: {}

networks:
  monitoring:
    driver: bridge
